---
title: "Assignment1"
author: "Melanie McCord"
date: "Spring 2024"
output: html_document
bibliography: assignment1_2.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Write 2-3 paragraphs to include the following information

- What is your data? Is it currently available? If not, how are you going to collect the data?

The data consists of every crime reported in the city of Chicago since 2001. The data is updated daily and can be accessed [here](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2/about_data), or alternatively through the City of Chicago API. Table 1 shows the original columns of the dataset and a brief description.

Some potential related datasets include:

-  [Community Economic Development](https://data.cityofchicago.org/Community-Economic-Development/Financial-Incentive-Projects-Small-Business-Improv/etqr-sz5x/about_data)

| ID                   | Unique identifier for the record.                                    |
|----------------------|----------------------------------------------------------------------|
| Case number          | Chicago id for the case number                                       |
| Date                 | Date when the incident occurred, this is sometimes a best estimate.  |
| Block                | The partially redacted address where the incident occurred.          |
| IUCR                 | The Illinois Uniform Crime Reporting Code.                           |
| Primary Type         | The primary description of the IUCR code.                            |
| Description          | The secondary description of the IUCR code.                          |
| Location description | The primary description of the location where the incident occurred. |
| Arrest               | Whether or not the incident resulted in an arrest.                   |
| Domestic             | Whether or not the incident was a domestic incident.                 |
| Beat                 | Indicates the beat where the incident occurred.                      |
| District             | The police district where the incident occurred.                     |
| Ward                 | The city council district where the incident occurred.               |
| Community Area       | The community area where the incident occurred.                      |
| FBI Code             | FBI Code crime classification.                                       |
| X Coordinate         | The X coordinate location where the incident occurred.               |
| Y coordinate         | The Y coordinate where the incident occurred.                        |
| Year                 | Year the incident occurred.                                          |
| Updated on           | Date and time the record was last updated.                           |
| Latitude             | The latitude where the incident occurred.                            |
| Longitude            | The longitude where the incident occurred.                           |
| Location             | The location of the incident. 

:  Table 1: Variables and descriptions of the Chicago Crimes Since 2001 dataset


- Why visualizing the data is important? Can I get insight by just looking at the data as a table? Why is this topic important?

Crime is a serious issue in American cities and across the world. The City of Chicago provides an extensive overview of every reported crime that occurred in Chicago since 2001 (~23 years to date) and updates it daily. Cities frequently do not publish their crime-related data publicly, so the City of Chicago's dataset, which is vast and extensive, is very valuable for understanding reported crimes in Chicago.

Further, crime is a complex and multi-faceted issue. There are potentially infinite research questions on crime. 
A few examples: How has the crime rate in Chicago changed over time? What are the most likely locations for the next crime in Chicago? How do the number of arrests compare between violent vs non-violent crimes?

Visualizing this data provides a way to understand some of these questions. Some visualization approaches can also guide modeling, e.g. crime prediction, that can be used to make forecasts.

__Dataset itself__:

This dataset is not really understandable as a table. Firstly, it's a very large dataset, and it's not practical or feasible to analyze the full details of 8 million crimes. (On a technical note, data munging or analyzing the raw dataset requires different approaches to conventional data analysis. Common approaches include parallel processing (e.g. GPU's) or distributed computing (i.e. distributing the tasks across multiple computers over the network)). Summary tables are possible; for example, the arrest variable could work, but in my opinion, visualizing the arrest variable in relationship to multiple other crimes would be easier to interpret as a visualization. The time series and spatial elements of the dataset are also easier to interpret with a visualization.