---
title: "Crime in Chicago"
subtitle: "A Data Visualization Project"
author: "Melanie McCord"
output: html_document
bibliography: initial_34_papers.bib
csl: ieee-transactions-on-visualization-and-computer-graphics.csl
---

#  Summary

The goal of this project is to examine the crime rate in the City of Chicago and its relationship with time and location (i.e. zip code and neighborhood).
Specifically, I will be visualizing a few key factors:

-  How has the crime rate changed over time from January 2001 (beginning of data collection) to the most recent date?
-  How does the crime rate relate to some other variables:
   -  the neighborhood where the incident was reported
   -  the demographics of the neighborhood
   -  the population density of the neigborhood and/or Chicago
   -  the unemployment rate in Chicago (overall) and the specific neighborhood (if available)
-  How does the proportion of arrests depend on:
   -  the category of crime (included in the dataset)
   -  crime itself (focusing on the top 5 most and least common)
-  (stretch goal) Special focus on gender-related crimes (e.g. domestic violence, sexual assault, stalking, etc.)
   -  How do the arrests and other factors of these crimes compare with the overall arrests and other factors?
   -  (additional stretch goal) => more detailed exploration of some related crimes, include brief page on that as well

#  Introduction

The Chicago crime dataset covers every crime that was reported to the Chicago police since 2001. @noauthor_crimes_nodate

| ID                   | Unique identifier for the record.                                    |
|----------------------|----------------------------------------------------------------------|
| Case number          | Chicago id for the case number                                       |
| Date                 | Date when the incident occurred, this is sometimes a best estimate.  |
| Block                | The partially redacted address where the incident occurred.          |
| IUCR                 | The Illinois Uniform Crime Reporting Code.                           |
| Primary Type         | The primary description of the IUCR code.                            |
| Description          | The secondary description of the IUCR code.                          |
| Location description | The primary description of the location where the incident occurred. |
| Arrest               | Whether or not the incident resulted in an arrest.                   |
| Domestic             | Whether or not the incident was a domestic incident.                 |
| Beat                 | Indicates the beat where the incident occurred.                      |
| District             | The police district where the incident occurred.                     |
| Ward                 | The city council district where the incident occurred.               |
| Community Area       | The community area where the incident occurred.                      |
| FBI Code             | FBI Code crime classification.                                       |
| X Coordinate         | The X coordinate location where the incident occurred.               |
| Y coordinate         | The Y coordinate where the incident occurred.                        |
| Year                 | Year the incident occurred.                                          |
| Updated on           | Date and time the record was last updated.                           |
| Latitude             | The latitude where the incident occurred.                            |
| Longitude            | The longitude where the incident occurred.                           |
| Location             | The location of the incident. 

:  Table 1: Variables and descriptions of the Chicago Crimes Since 2001 dataset


#  Related Work

The City of Chicago's crime dataset is fairly extensive. It covers every reported crime since 2001, updated daily. This dataset has a variety of uses. It has numerous variables relating to the individual occurrence of crimes, including location, time reported, and whether an arrest occurred. Hence, it is a dataset that can be used either alone or in combination with other related datasets for potentially infinite crime-related research questions.

Two example research questions that can be aided by visualization are generating safe routes based on crime prediction data @noauthor_safe_nodate and @kim_effect_2023

#  Motivation

#  Data

The dataset is the publicly available Chicago crime dataset. @n_chicago_2019 

#  Goals

##  Technical Requirements
The website will be created using React 18.2.0. @facebook_react_2024 The visualizations will be created using D3 @bostock_d3js_2012. The backend will be done in Node.JS 20.11.1. @nodejs_nodejs_2024.

#  Website Functional Specifications

#  Website Pages (overview)

-  Main page

#  Timeline and Activities

#  Conclusion

# References